/**
 * types/agent.ts
 *
 * Shared types for the Hollis Agent Tier System.
 *
 * The tier system is a decision gate that sits between the cron job firing
 * and the action being taken. It reads inbound signals, classifies intent,
 * writes renewal flags, and routes to the appropriate tier.
 */

// ── Renewal Flags ──────────────────────────────────────────────────────────────
// Set by: inbound parser, manual broker input, or cron job.
// Stored as JSONB in policies.renewal_flags.

export type RenewalFlags = {
  active_claim: boolean;
  insurer_declined: boolean;
  premium_increase_pct: number | null;  // e.g. 42 = 42% increase; null = not detected
  business_restructure: boolean;
  third_party_contact: boolean;         // reply came from non-policy contact
  silent_client: boolean;               // no engagement within threshold (set by cron)
  call_script_rejected: boolean;        // broker explicitly rejected the call script touchpoint
  days_to_expiry: number;               // computed at runtime, not persisted in JSONB
};

export const DEFAULT_RENEWAL_FLAGS: RenewalFlags = {
  active_claim: false,
  insurer_declined: false,
  premium_increase_pct: null,
  business_restructure: false,
  third_party_contact: false,
  silent_client: false,
  call_script_rejected: false,
  days_to_expiry: 0,
};

// ── Intent Taxonomy ────────────────────────────────────────────────────────────

// Intents the agent can act on autonomously (Tier 1)
// v2 names are the canonical names; v1 names kept for backward compat with
// existing records in approval_queue, parser_outcomes, inbound_signals.
export const KNOWN_AUTONOMOUS_INTENTS = [
  // v2 canonical names
  "confirmed",          // replaces confirm_renewal
  "coverage_question",  // replaces soft_query
  // v1 names (kept for backward compat — no longer generated by classifier)
  "confirm_renewal",
  "soft_query",
  // unchanged
  "request_callback",
  "document_received",
  "out_of_office",
] as const;

export type AutonomousIntent = (typeof KNOWN_AUTONOMOUS_INTENTS)[number];

// Intents that always require Tier 2 broker action (not escalation).
// The broker must complete a real-world task before the renewal can proceed.
// Learning cannot graduate these to Tier 1.
export const ALWAYS_BROKER_REVIEW_INTENTS: string[] = [
  // v2 canonical names
  "price_objection",            // Client has premium concerns — broker must respond
  "material_change_disclosed",  // Business change alongside renewal — broker must verify before binding
  "prior_comms_reference",      // Client references email/call not visible in thread — broker must check history
  // unchanged
  "document_required",          // Agent detected a document is needed — broker approves before chase starts
  "ambiguous_acknowledgement",  // "Thanks", "Got it", "OK" — intent unclear, broker to review
  // v1 names (kept for backward compat — no longer generated by classifier)
  "renewal_with_changes",
  "schedule_meeting",
];

// Intents that ALWAYS escalate to Tier 3, regardless of confidence score.
// This list is immutable — learning cannot graduate these to Tier 1.
export const ALWAYS_ESCALATE_INTENTS: string[] = [
  // v2 canonical names
  "declined_churn",       // Client explicitly leaving for another broker — retention escalation
  "contact_change",       // Client requests contact update — must be done before sequence continues
  "forwarded_no_intent",  // Email was a forward — never reply, surface to broker
  // v1 names (kept for backward compat — no longer generated by classifier)
  "active_claim_mentioned",
  "insurer_declined",
  "premium_increase_major",
  "business_restructure",
  "cancel_policy",
  "legal_dispute_mentioned",
  "unverified_third_party",
];

// Full set of known intents (autonomous + broker-review + escalate)
export const ALL_KNOWN_INTENTS: string[] = [
  ...(KNOWN_AUTONOMOUS_INTENTS as readonly string[]),
  ...ALWAYS_BROKER_REVIEW_INTENTS,
  ...ALWAYS_ESCALATE_INTENTS,
];

// ── Intent Classification ──────────────────────────────────────────────────────

export interface ClassificationResult {
  intent: string;
  confidence: number;                    // 0.000 to 1.000
  flags_detected: string[];              // flag names detected in signal (active_claim, insurer_declined, etc.)
  premium_increase_pct: number | null;   // extracted if a premium increase was detected
  reasoning: string;                     // brief explanation for audit trail
  // v2 fields
  extracted_context?: string | null;     // key facts from the reply for broker task body
  ooo_alt_contact?: string | null;       // alt contact email extracted from OOO message
  // existing optional fields
  changes_requested?: string[];          // populated when intent is renewal_with_changes / material_change_disclosed
  document_type_needed?: string | null;  // populated when intent is document_required
  secondary_flags?: string[];            // compound signals alongside primary intent
  ooo_return_date?: string | null;       // ISO date extracted from OOO message
}

// ── Inbound Signals ────────────────────────────────────────────────────────────

export interface InboundSignal {
  id: string;
  policy_id: string;
  user_id: string;
  raw_signal: string;
  sender_email: string | null;
  sender_name: string | null;
  source: "manual" | "email" | "sms";
  processed: boolean;
  processed_at: string | null;
  classification_result: ClassificationResult | null;
  created_at: string;
}

// ── Parser Outcomes (Learning Layer) ──────────────────────────────────────────
// Every Tier 2 broker resolution writes here.
// Top 10 broker-approved outcomes are injected as few-shot examples into
// the classifier prompt at Step 8.

export interface ParserOutcome {
  id: string;
  renewal_id: string | null;
  signal_id: string | null;
  user_id: string;
  raw_signal: string;
  classified_intent: string;
  confidence_score: number;
  broker_action: "approved" | "rejected" | "edited" | null;
  final_intent: string | null;
  created_at: string;
}

// ── Approval Queue (Tier 2) ────────────────────────────────────────────────────

export interface ProposedAction {
  description: string;                    // human-readable summary for the broker
  action_type: string;                    // e.g. 'advance_stage', 'send_email', 'create_task'
  task_type?: string;                     // broker task category for approval_queue.task_type column
  payload: Record<string, unknown>;
}

export interface BrokerDecision {
  action: "approved" | "rejected" | "edited";
  edited_intent?: string;
  notes?: string;
}

export interface ApprovalQueueItem {
  id: string;
  policy_id: string;
  user_id: string;
  signal_id: string | null;
  classified_intent: string;
  confidence_score: number;
  raw_signal_snippet: string;
  proposed_action: ProposedAction;
  status: "pending" | "approved" | "rejected" | "edited";
  broker_decision: BrokerDecision | null;
  resolved_at: string | null;
  created_at: string;
}

// ── Tier Routing ───────────────────────────────────────────────────────────────

export type TierLevel = 1 | 2 | 3;

export interface BrokerNotification {
  title: string;
  flag_reason: string;
  policy_id: string;
  client_name: string;
  policy_name: string;
  expiry_date: string;
  last_touchpoint_at: string | null;
  last_message_snippet: string;
  options: ("resume_sequence" | "mark_handled" | "call_client")[];
}

export interface TierDecision {
  tier: TierLevel;
  reason: string;
  classification: ClassificationResult;
  flags: RenewalFlags;
  // Tier 3
  broker_notification?: BrokerNotification;
  // Tier 2
  approval_queue_id?: string;
  proposed_action?: ProposedAction;
  // Tier 1
  autonomous_action?: string;
}
