/**
 * GET  /api/renewals/[id]/questionnaire  — list questionnaires for a policy
 * POST /api/renewals/[id]/questionnaire  — send questionnaire to client
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { getResendClient } from "@/lib/resend/client";
import { QUESTIONNAIRE_QUESTIONS } from "@/lib/renewals/questionnaire";
import { writeAuditLog } from "@/lib/audit/log";

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data, error } = await supabase
    .from("renewal_questionnaires")
    .select("*")
    .eq("policy_id", id)
    .eq("user_id", user.id)
    .order("created_at", { ascending: false });

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json(data ?? []);
}

export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // Fetch policy
  const { data: policy, error: policyErr } = await supabase
    .from("policies")
    .select("id, policy_name, client_name, client_email, carrier, expiration_date, user_id")
    .eq("id", id)
    .eq("user_id", user.id)
    .single();
  if (policyErr || !policy) return NextResponse.json({ error: "Policy not found" }, { status: 404 });
  if (!policy.client_email) return NextResponse.json({ error: "Policy has no client email" }, { status: 400 });

  // Create questionnaire record (token generated by DB default)
  const { data: questionnaire, error: qErr } = await supabase
    .from("renewal_questionnaires")
    .insert({ policy_id: id, user_id: user.id })
    .select("id, token")
    .single();
  if (qErr || !questionnaire) {
    return NextResponse.json({ error: qErr?.message ?? "Failed to create questionnaire" }, { status: 500 });
  }

  const questionnaireUrl = `${process.env.NEXT_PUBLIC_APP_URL ?? "https://app.hollis.ai"}/q/${questionnaire.token}`;

  // Fetch agent profile
  const { data: profile } = await supabase
    .from("agent_profiles")
    .select("first_name, last_name, phone")
    .eq("user_id", user.id)
    .single();
  const agentName = profile
    ? [profile.first_name, profile.last_name].filter(Boolean).join(" ") || user.email!
    : (user.email ?? "Your Broker");
  const agentPhone = profile?.phone ?? "";

  // Build the email
  const questionList = QUESTIONNAIRE_QUESTIONS.map((q, i) => `${i + 1}. ${q.label}`).join("\n");
  const subject = `${policy.policy_name} renewal — a quick update from your broker`;
  const body = `Dear ${policy.client_name},

Your ${policy.policy_name} with ${policy.carrier} is coming up for renewal. To make sure we get you the best possible terms, I'd like to check whether anything has changed in your business over the past 12 months.

This takes about 2 minutes. Please click the link below to complete the update:

${questionnaireUrl}

The form asks about:
${questionList}

Please complete this by ${new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" })} so we have enough time to go to market on your behalf.

If you have any questions, please call me directly.

${agentName}
${user.email}
${agentPhone}`;

  // Send via Resend
  let providerId: string | null = null;
  try {
    const resend = getResendClient();
    const { data: sent } = await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL ?? "noreply@hollis.ai",
      to: policy.client_email,
      subject,
      text: body,
    });
    providerId = sent?.id ?? null;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: `Email send failed: ${msg}` }, { status: 500 });
  }

  // Create a campaign touchpoint record
  const today = new Date().toISOString().split("T")[0];
  await supabase.from("campaign_touchpoints").insert({
    policy_id: id,
    user_id: user.id,
    type: "questionnaire_90",
    status: "sent",
    subject,
    content: body,
    scheduled_at: today,
    sent_at: new Date().toISOString(),
  });

  // Advance stage
  await supabase
    .from("policies")
    .update({ campaign_stage: "questionnaire_sent", last_contact_at: new Date().toISOString() })
    .eq("id", id)
    .eq("user_id", user.id);

  // Write audit log
  await writeAuditLog({
    supabase,
    policy_id: id,
    user_id: user.id,
    event_type: "questionnaire_sent",
    channel: "email",
    recipient: policy.client_email,
    content_snapshot: `Subject: ${subject}\n\n${body}`,
    metadata: {
      questionnaire_id: questionnaire.id,
      questionnaire_url: questionnaireUrl,
      provider_id: providerId,
    },
    actor_type: "agent",
  });

  return NextResponse.json({
    questionnaire_id: questionnaire.id,
    token: questionnaire.token,
    url: questionnaireUrl,
    sent_to: policy.client_email,
  }, { status: 201 });
}
